// This file contains error codes used by the
// BioTek Instruments, Inc product: Gen5
// Translated from BTIStatusCodes.h

namespace LMSF_Gen5_Reader
{
    enum BTIStatusCodes
    {
        // General purpose codes
        BTI_OK = 1,
        BTI_FAIL = -1,
        BTI_UNKNOWN_STATUS = -2,
        BTI_USER_CANCELLED_OPERATION = -3,
        BTI_UNABLE_TO_START_TIMER = -4,
        BTI_INVALID_REQUEST = -5,
        BTI_UNABLE_TO_PROCESS_REQUEST = -6,
        BTI_MEMORY_ALLOC_ERROR = -7,
        BTI_UNKNOWN_CHARACTERISTIC_ID = -8,


        // -100 to -199 File Processing
        BTI_FILE_DOES_NOT_EXIST = -100,
        BTI_UNABLE_TO_OPEN_FILE = -101,
        BTI_FILE_ALREADY_EXISTS = -102,
        BTI_FILE_READ_ONLY = -103,
        BTI_INVALID_PATHNAME = -104,
        BTI_FILE_LOCKED = -105,
        BTI_FILE_SHARING_VIOLOATION = -106,
        BTI_FILE_WRITE_ERROR = -107,
        BTI_FILE_READ_ERROR = -108,
        BTI_READ_FROM_FILE_EOF_ERROR = -109,
        BTI_READ_FROM_FILE_TIME_STAMP_NOT_FOUND = -110,

        // -200 to -299 Record Parsing
        BTI_INVALID_RECORD_FORMAT = -200,
        BTI_INVALID_PARAMETER_LIST = -201,
        BTI_UNKNOWN_RECORD_TYPE = -202,

        // -300 to -399 Field Parsing Errors
        BTI_INVALID_FIELD_OPTION = -300,
        BTI_FIELD_BELOW_MIN_RANGE = -301,
        BTI_FIELD_ABOVE_MAX_RANGE = -302,
        BTI_FIELD_TOO_LONG = -303,
        BTI_FIELD_TOO_SHORT = -304,

        // -400 to -449 Object-Specific Errors
        BTI_OBJECT_CREATION_ERROR = -400,
        BTI_OBJECT_DOES_NOT_EXIST = -401,
        BTI_INSUFFICIENT_FIELDS = -402,
        BTI_NAME_REQUIRED = -403,

        // -450 to -499 OLEDispatch Errors
        BTI_DEVICE_PROXY_CREATION_ERROR = -450,
        BTI_DEVICE_MGR_NO_AVAIL_READERS = -451,

        // -500 to -599 Serial Communication Errors
        BTI_BAUD_RATE_INVALID = -500,
        BTI_DATA_BITS_INVALID = -501,
        BTI_STOP_BITS_INVALID = -502,
        BTI_PARITY_INVALID = -503,
        BTI_SERIAL_PORT_ERROR = -504,   //Serial port setup failed
        BTI_SERIAL_WRITE_ERROR = -505,  //failure to write out correct number of bytes
        BTI_SERIAL_READ_ERROR = -506,   //time-out or failure to read in correct number of bytes
        BTI_CHECKSUM_ERROR = -507,
        BTI_SERIAL_NAK_ERROR = -508,
        BTI_EXCESS_DATA_RECEIVED = -509,    //instrument return more data than expected
        BTI_INVALID_MSG_OBJECT = -510,
        BTI_INVALID_MSG_BODY_SIZE = -511,
        BTI_PURGE_COMM_FAILURE = -512,
        BTI_PORT_NOT_OPEN = -513,
        BTI_PORT_HANDLE_ERROR = -514,
        BTI_SERIAL_STREAM_ERROR = -515, //data received not format expected 
        BTI_SEND_CMD_HEADER_ERROR = -516,
        BTI_SEND_CMD_BODY_ERROR = -517,
        BTI_RECEIVE_CMD_BODY_ERROR = -518,
        BTI_RECEIVE_CMD_STATUS_ERROR = -519,
        BTI_RECEIVE_BODY_SIZE_MISMATCH = -520,
        BTI_RECEIVE_STATUS_SIZE_MISMATCH = -521,
        BTI_COM_PORT_ALREADY_IN_USE = -522,
        BTI_SET_TIMEOUT_ERROR = -523,
        BTI_SET_DCB_BLOCK_FAILURE = -524,
        BTI_CREATE_FILE_HANDLE_ERROR = -525,
        BTI_CREATE_FILE_NO_PORT_ERROR = -526,
        BTI_CREATE_FILE_PORT_IN_USE = -527,
        BTI_COULD_NOT_MATCH_BAUD_RATE = -528,

        // -600 to -699 Reader Specific Errors
        BTI_UNKNOWN_READER = -600,
        BTI_READER_STATUS_ERROR = -601,
        BTI_READER_NO_ACKNOWLEDGE = -602,
        BTI_TEMP_RANGE_NOT_FOUND = -603,
        BTI_ELX_STATUS_NOT_SUPPORTED = -604,
        BTI_GEOMETRY_INVALID = -605,
        BTI_READ_TIMEOUT_ERROR = -606,  //reader failed to respond within expected time
        BTI_ABS_READER_DATA_NEW_ERROR = -607,
        BTI_READER_INV_WAVELENGTH = -608,
        BTI_READER_INV_NUM_FILTER_SETS = -609,
        BTI_FLUOR_READER_DATA_NEW_ERROR = -610,
        BTI_READER_COMMANDS_NULL = -611,
        BTI_FLUOR_DATA_PARSE_FAILURE = -612,
        BTI_SPECTRAL_SCAN_DATA_NEW_ERROR = -613,
        BTI_SPECTRAL_SCAN_DATA_STATE_ERROR = -614,
        BTI_AREA_SCAN_DATA_NEW_ERROR = -615,
        BTI_LINEAR_SCAN_DATA_NEW_ERROR = -616,
        BTI_AREA_LINEAR_SCAN_DATA_NEW_ERROR = -617,
        BTI_READER_VERSION_NOT_SUPPORTED = -618,
        BTI_READ_TYPE_NOT_VALID = -619,


        BTI_GET_SENSITIVITY_INVALID_FILTER_SET = -620,
        BTI_SET_PROBE_HEIGHT_INVALID_HEIGHT = -621,
        BTI_SET_PROBE_HEIGHT_INVALID_SELECTION = -622,
        BTI_INCUBATION_TEMP_INVALID = -623,
        BTI_INCUBATION_NOT_SUPPORTED = -624,
        BTI_FLUOR_LUMIN_S_CMD_RSP_DATA_ERR = -625,
        BTI_CFLUORESCENCEREADERDATA_ERROR = -626,
        BTI_FLUOR_LUMIN_DATA_CHECKSUM_ERROR = -627,
        BTI_SYSTEM_TEST_NOT_SUPPORTED = -628,
        BTI_SYSTEM_TEST_TIMER_READ_DATA_FAIL = -629,
        BTI_MSG_DIALOG_START_TIMER_FAILED = -630,
        BTI_TIMEOUT_ERROR = -631,
        BTI_ABORT_ERROR = -632,
        BTI_NO_ENDPOINT_DATA_PRESENT = -633,
        BTI_ABSORBANCE_DATA_CHECKSUM_ERROR = -634,
        BTI_NO_SPECTRAL_SCAN_DATA_PRESENT = -635,
        BTI_UNDEFINED_SPECTRAL_VALUE = -636,
        BTI_SPECTRAL_DATA_CHECKSUM_ERROR = -637,
        BTI_SPECTRAL_DATA_COMMAND_ERROR = -638,
        BTI_NO_AREA_SCAN_DATA_PRESENT = -639,
        BTI_READER_IN_USE = -640,
        BTI_EXECUTE_READ_PARAM_TRY_CATCH = -641,
        BTI_NO_MONITOR_WELL_DATA_PRESENT = -642,
        BTI_AUXILIARY_DATA_PRESENT = -643,
        BTI_AUXILIARY_DATA_TRY_CATCH = -644,
        BTI_NO_AUXILIARY_DATA_PRESENT = -645,
        BTI_NO_WELL_DATA_PRESENT = -646,
        BTI_READER_DATA_PRESENT = -647,
        BTI_NO_SENSITIVITY_VALUE_MATCH = -648,
        BTI_EDIT_READ_PARAM_TRY_CATCH = -649,

        // Errors specific to capabilities
        BTI_RDR_NO_ABSORBANCE_SUPPORT = -650,
        BTI_RDR_NO_FLUORESCENCE_SUPPORT = -651,
        BTI_RDR_NO_LUMINESCENCE_SUPPORT = -652,
        BTI_RDR_MIN_WAVELENGTH_EXCEEDED = -653,
        BTI_RDR_MAX_WAVELENGTH_EXCEEDED = -654,
        BTI_RDR_NO_INCUBATION_SUPPORT = -655,
        BTI_RDR_MIN_TEMP_EXCEEDED = -656,
        BTI_RDR_MAX_TEMP_EXCEEDED = -657,
        BTI_RDR_NO_SHAKE_SUPPORT = -658,
        BTI_FEATURE_NOT_IMPLEMENTED = -659,
        BTI_PROBE_HEIGHT_OUT_OF_RANGE = -660,
        BTI_RDR_REQUIRES_SPECIFIC_PROTOCOL = -661,
        BTI_PROTOCOL_REQUIRES_SPECIFIC_RDR = -662,
        BTI_RDR_NO_SPECTRUM_SCAN_SUPPORT = -663,
        BTI_RDR_NO_AREA_SCAN_SUPPORT = -664,
        BTI_RDR_NO_LINEAR_SCAN_SUPPORT = -665,
        BTI_RDR_NO_DISPENSER_SUPPORT = -666,
        BTI_RDR_MAX_DISPENSERS_EXCEEDED = -667,
        BTI_RDR_NO_WELL_MODE_SUPPORT = -668,
        BTI_RDR_WELL_MODE_READS_EXCEEDED = -669,
        BTI_RDR_WELL_MODE_SHAKES_EXCEEDED = -670,
        BTI_RDR_WELL_MODE_DISPENSES_EXCEEDED = -671,
        BTI_RDR_NO_SYNC_PLATE_MODE_SUPPORT = -672,
        BTI_RDR_SYNC_PLATE_MODE_READS_EXCEEDED = -673,
        BTI_RDR_SYNC_PLATE_MODE_SHAKES_EXCEEDED = -674,
        BTI_RDR_SYNC_PLATE_MODE_DISPNS_EXCEEDED = -675,
        BTI_RDR_SYNC_PLATE_MODE_STEPS_EXCEEDED = -676,
        BTI_RDR_NO_PATHLEN_CORRECTION_SUPPORT = -677,
        BTI_DATA_FORMAT_ERROR = -678,
        BTI_KINETIC_DURATION_LESS_THAN_INTERVAL = -679,

        // RESERVE NUMBERS -680 to -699

        // Other Errors
        BTI_NO_PLATE_TYPE_DEFINED = -700,
        BTI_UNSUPPORTED_READ_PARAM_STEP = -701,
        BTI_INVALID_ORDER_PAUSE_STEP = -702,
        BTI_INVALID_ORDER_INCUBATE_STEP = -703,
        BTI_INVALID_ORDER_CARRIER_IN_OUT_STEP = -704,
        BTI_INVALID_ORDER_READ_STEP = -705,
        BTI_INVALID_ORDER_KINETIC_END_STEP = -706,
        BTI_NO_READ_PARAMETERS = -707,
        BTI_INVALID_RESUME_INDEX = -708,
        BTI_INSUFFICIENT_KINETIC_READ_PARAMS = -709,
        BTI_NO_KINETIC_SCANS_ALLOWED = -710,
        BTI_AUTOSENSITIVITY_ERROR = -711,
        BTI_STOP_RESUME_LAST_STEP_ERROR = -712,
        BTI_STOP_RESUME_NEXT_STEP_ERROR = -713,
        BTI_ILLEGAL_PRODUCT_DELINEATION_SETTING = -714,
        BTI_READER_CONFIG_NOT_SUPPORTED_PD = -715,  // product delineation doesn't allow reader configuration
        BTI_DISPENSE_MEASURE_NOT_SUPPORTED = -716,
        BTI_INVALID_MESSAGE_RESP_SIZE = -717,
        BTI_E_COMMAND_CHECKSUM_FAILURE = -718,
        BTI_E_COMMAND_RATES_SUPPORTED_ERROR = -719,
        BTI_INVALID_ORDER_MODE_END_STEP = -720,
        BTI_MAX_G_COMMAND_TOTAL_EVENTS_EXCEEDED = -721,
        BTI_MAX_G_COMMAND_SHAKE_EVENTS_EXCEEDED = -722,
        BTI_MAX_G_COMMAND_READ_EVENTS_EXCEEDED = -723,
        BTI_MAX_G_COMMAND_DISPENSE_EVENTS_EXCEEDED = -724,
        BTI_ILLEGAL_STEP_TYPE_FOUND_IN_BLOCK = -725,
        BTI_G_COMMAND_MISMATCH_RESPONSE_SIZE = -726,
        BTI_G_COMMAND_CHECKSUM_FAILURE = -727,
        BTI_INVALID_ORDER_MONITOR_WELL_END_STEP = -728,
        BTI_DISPENSER1_NOT_PRIMED = -729,
        BTI_DISPENSER2_NOT_PRIMED = -730,
        BTI_INVALID_WELL_MODE_EVENT_TYPE = -731,
        BTI_INVALID_PLATE_MODE_EVENT_TYPE = -732,
        BTI_WELL_MODE_DATA_ERROR = -732,
        BTI_WELL_MODE_EVENT_MISMATCH_ERROR = -734,
        BTI_WELL_MODE_END_OF_WELL_ERROR = -735,
        BTI_WELL_MODE_HEADER_ERROR = -736,
        BTI_WELL_MODE_DELAY_FROM_START_ERROR = -737,
        BTI_AREA_SCAN_PROBE_SIZE_CHANGED = -738,
        BTI_AREA_SCAN_SPACING_SIZE_CHANGED = -739,
        BTI_AREA_SCAN_MATRIX_SIZE_CHANGED = -740,
        BTI_BIOCELL_READ_FROM_FILE_ERROR = -741,
        BTI_Y_COMMAND_CHECKSUM_FAILURE = -742,
        BTI_UNKNOWN_DETECTION_METHOD = -743,
        BTI_BLOCK_MODE_DELAY_ERROR = -744,
        BTI_FLX800_WELL_MODE_OPERATION_ERROR = -745,
        BTI_ABS_KINETIC_INTERVAL_ERROR = -746,
        BTI_FLUORLUMIN_KINETIC_INTERVAL_ERROR = -747,
        BTI_WELL_MODE_KINETIC_INTERVAL_ERROR = -748,
        BTI_FLX800_DELAY_STEP_REQUIRED_WELL_MODE = -749,
        BTI_FLX800_DELAY_STEP_FROM_START = -750,
        BTI_FLX800_DISPENSE_LAST_ERROR = -751,
        BTI_FLX800_KINETIC_READ_REQUIRED = -752,
        BTI_FLX800_KINETIC_INTERVAL_SAME_ERROR = -753,
        BTI_DISPENSERS_NOT_PRIMED = -754,
        BTI_WELL_MODE_DELAY_TOO_SHORT = -755,
        BTI_USER_OVERRIDE_SET_TEMPERATURE = -756,
        BTI_INVALID_READER_TYPE = -757,
        BTI_LUMINESCENCE_DATA_FORMAT_ERROR = -758,
        BTI_NO_WELL_MODE_SIMULATION = -759,
        BTI_NO_PLATE_SYNCH_MODE_SIMULATION = -760,
        BTI_EVENT_START_TIME_EXCEEDS_LIMIT = -761,
        BTI_WELL_MODE_KINETIC_INTERVAL_EXCEEDED = -762,
        BTI_PLATE_MODE_KINETIC_INTERVAL_EXCEEDED = -763,
        BTI_STAND_ALONE_SHAKE_NOT_SUPPORTED = -764,
        BTI_MONITOR_WELL_ILLEGAL_DEFINITION = -765,
        BTI_NO_APPEND_IN_MULTIMODE_BLOCK = -766,
        BTI_FLUORESCENCE_DATA_TERMINATOR_INVALID = -767,
        BTI_MULTI_MODE_KINETIC_INTERVAL_EXCEEDED = -768,
        BTI_OLD_STATUS_FORMAT = -769,
        BTI_FLX800_PLATE_SYNCH_NUM_KINETIC_READS = -770,
        BTI_FLX800_WELL_SYNCH_NUM_KINETIC_READS = -771,
        BTI_SYNERGY_WELL_SYNCH_NUM_KINETIC_READS = -772,
        BTI_SYNERGY_PLATE_SYNCH_NUM_KINETIC_READS = -773,
        BTI_MULTI_MODE_NUM_KINETIC_READS_ERROR = -774,
        BTI_FLUORESCENCE_KINETIC_READS_ERROR = -775,
        BTI_ABSORBANCE_KINETIC_READS_ERROR = -776,
        BTI_KINETIC_DURATION_VS_INTERVAL_ERROR = -777,
        BTI_ERROR_DETECTED_DURING_BULB_WARMUP = -778,

        // Clarity Errors
        BTI_CLARITY_CREATE_DISPATCH_ERROR = -800,
        BTI_CLARITY_OPEN_PROTOCOL_ERROR = -801,
        BTI_CLARITY_CLOSE_PROTOCOL_ERROR = -802,
        BTI_CLARITY_START_PROTOCOL_ERROR = -803,
        BTI_CLARITY_FILE_NOT_FOUND = -804,
        BTI_CLARITY_FILE_MODIFIED = -805,
        BTI_CLARITY_FILE_READ_ERROR = -806,
        BTI_CLARITY_MOVE_PLATE_ERROR = -807,
        BTI_CLARITY_SIMULATION_NOT_SUPPORTED = -808,

        /////////////////////////////////////////////////////////////////////////
        // Automation Error Codes -2000 to -3000
        /////////////////////////////////////////////////////////////////////////
        // General error codes (-2000 to -2099)
        BTI_AUTM_DOCUMENT_ALREADY_IN_MEMORY = -2010,
        BTI_AUTM_INVALID_INDEX = -2011,

        // Generic storage layer errors
        BTI_AUTM_DATABASE_GENERIC_ERROR = -2012,
        BTI_AUTM_FILE_GENERIC_ERROR = -2013,
        BTI_AUTM_FILE_FILE_NOT_FOUND = -2014, // The file could not be located 
        BTI_AUTM_FILE_BAD_PATH = -2015,// All or part of the path is invalid

        // Application methods (-2100 to -2299)
        BTI_AUTM_APP_NEW_EXP_GENERIC_ERROR = -2100,
        BTI_AUTM_APP_OPEN_EXP_GENERIC_ERROR = -2101,
        BTI_AUTM_APP_SET_CLIENT_WINDOW_GENERIC_ERROR = -2120,
        BTI_AUTM_APP_BROWSE_FOR_FILE_GENERIC_ERROR = -2130,
        BTI_AUTM_APP_BROWSE_FOR_FOLDER_GENERIC_ERROR = -2140,
        BTI_AUTM_APP_READER_OPERATION_READER_NOT_CONFIGURED = -2145,
        BTI_AUTM_APP_CONFIGURE_OLE_READER_GENERIC_ERROR = -2150,
        BTI_AUTM_APP_CONFIGURE_COM_READER_GENERIC_ERROR = -2160,
        BTI_AUTM_APP_CONFIGURE_COM_READER_INVALID_READER_TYPE = -2161,
        BTI_AUTM_APP_CONFIGURE_COM_READER_INVALID_COM_PORT = -2162,
        BTI_AUTM_APP_CONFIGURE_COM_READER_INVALID_BAUD_RATE = -2163,
        BTI_AUTM_APP_CARRIER_IN_GENERIC_ERROR = -2170,
        BTI_AUTM_APP_CARRIER_OUT_GENERIC_ERROR = -2180,

        // Experiment methods (-2300 to -2399)
        BTI_AUTM_EXP_PLATES_GENERIC_ERROR = -2300,
        BTI_AUTM_EXP_SAVE_GENERIC_ERROR = -2310,
        BTI_AUTM_EXP_SAVE_AS_GENERIC_ERROR = -2320,
        BTI_AUTM_EXP_CLOSE_GENERIC_ERROR = -2330,
        BTI_AUTM_EXP_EXPERIMENT_IS_CLOSED = -2331,

        // Plates methods (-2400 to -2499)
        BTI_AUTM_PLATES_GET_PLATE_GENERIC_ERROR = -2400,
        BTI_AUTM_PLATES_ADD_MULTI_PLATE_ASSAY_PROTOCOL = -2410,
        BTI_AUTM_PLATES_ADD_GENERIC_ERROR = -2420,

        // Plate methods (-2500 to -2599)
        BTI_AUTM_PLATE_START_READ_GENERIC_ERROR = -2500,
        BTI_AUTM_PLATE_RESUME_READ_READ_NOT_PAUSED = -2501,
        BTI_AUTM_PLATE_READ_FROM_FILE_INVALID_SEPARATOR = -2502,
        BTI_AUTM_PLATE_ABORT_READ_GENERIC_ERROR = -2510,
        BTI_AUTM_PLATE_DELETE_GENERIC_ERROR = -2520,
        BTI_AUTM_PLATE_DELETE_MULTI_PLATE_ASSAY_PROTOCOL = -2521,
        BTI_AUTM_PLATE_DELETE_PLATE_IS_CALIBRATE = -2522,
        BTI_AUTM_PLATE_DELETE_LAST_PLATE = -2523,
        BTI_AUTM_PLATE_PLATE_IS_DELETED = -2524,
        BTI_AUTM_PLATE_POWER_EXPORT_GENERIC_ERROR = -2530,
        BTI_AUTM_PLATE_POWER_EXPORT_NOT_DEFINED = -2531,
        BTI_AUTM_PLATE_FILE_EXPORT_GENERIC_ERROR = -2540,
        BTI_AUTM_PLATE_FILE_EXPORT_NOT_DEFINED = -2541,
        BTI_AUTM_PLATE_PRINT_REPORT_GENERIC_ERROR = -2550,
        BTI_AUTM_PLATE_PRINT_REPORT_NOT_DEFINED = -2551,
    }
    /*

	public class BTIStatusCodes
	{
        // General purpose codes
		const int BTI_OK						= 1;
		const int BTI_FAIL						= -1;
		const int BTI_UNKNOWN_STATUS			= -2;
		const int BTI_USER_CANCELLED_OPERATION	= -3;
		const int BTI_UNABLE_TO_START_TIMER		= -4;
		const int BTI_INVALID_REQUEST			= -5;
		const int BTI_UNABLE_TO_PROCESS_REQUEST	= -6;
		const int BTI_MEMORY_ALLOC_ERROR		= -7;
		const int BTI_UNKNOWN_CHARACTERISTIC_ID	= -8;
	}
	*/

    enum EReaderStatus
    {
        eReaderStatus_OK = 0,
        eReaderStatus_Busy = -1,
        eReaderStatus_NotCommunicating = -2,
        eReaderStatus_NotConfigured = -3,
    }
}